# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 365d6a5e209da0792a1518a6c8c4cbdf71b9751dc8edd61a6faa73b4965c4d33a556c8c41aa8cd214916db60cf97e2a050dddec2ccce482c1b9014266c0fb1a7

test:
  secret_key_base: 1f4f8a2f39c962a921ee0b340fbb7f63275383db940aa8b0e9b64b2b4571bc3c585b3046b5700a2dd9648bcbdcbd0a832f40c04ef97d5ef82ad65d0d0d763393

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
